/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.coffee.ui;

import com.coffee.dao.HoaDonCTDAO;
import com.coffee.dao.HoaDonDAO;
import com.coffee.entity.HoaDon;
import com.coffee.entity.HoaDonCT;
import com.coffee.utils.Auth;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOANG HUU
 */
public class Hoadonctform extends javax.swing.JPanel {

    /**
     * Creates new form Hoadonct
     */
    public Hoadonctform() {
        initComponents();
        fillTable();
    }
    
     HoaDonDAO hoaDon = new HoaDonDAO();
    List<HoaDon> list = hoaDon.selectAll();
    HoaDonCTDAO hoaDonCT = new HoaDonCTDAO();
    List<HoaDonCT> listCT = hoaDonCT.selectAll();
    HoaDonCTDAO daoHDCT = new HoaDonCTDAO();
     
    int viTri;
    
    public void fillTable() {
       DefaultTableModel model = (DefaultTableModel) tblHoadonct.getModel();
        model.setRowCount(0);
      
            
           

       for (com.coffee.entity.HoaDonCT hd : listCT) {
            Object[] rows = new Object[]{hd.getMaHD(),hd.getMaHDCT(),hd.getMaSP(),hd.getSoLuong(),hd.getGiamGia(),hd.getDonGia()

            };
            model.addRow(rows);
        }

    
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBanHang = new javax.swing.JScrollPane();
        tblHoadonct = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        panelBanHang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 3, 3, 3, new java.awt.Color(123, 189, 255)));

        tblHoadonct.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(255, 0, 51)));
        tblHoadonct.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblHoadonct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MaHD", "MaHDCT", "MaSP", "Số lượng", "Giảm giá", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoadonct.setFocusable(false);
        tblHoadonct.setRowHeight(25);
        tblHoadonct.setSelectionBackground(new java.awt.Color(255, 0, 51));
        tblHoadonct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoadonctMouseClicked(evt);
            }
        });
        panelBanHang.setViewportView(tblHoadonct);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Hóa Đơn Chi Tiết");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(panelBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoadonctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoadonctMouseClicked

    }//GEN-LAST:event_tblHoadonctMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane panelBanHang;
    private javax.swing.JTable tblHoadonct;
    // End of variables declaration//GEN-END:variables
}
